name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
